name: Nodejs Setup

on:  
   push:
      branches: [ "main" ]

jobs:
  build:
   runs-on: ubuntu-latest
   name: Install NodeJs


   steps:
     - name: Checkout Code
       uses: actions/checkout@v4

     - name: Setup Node
       uses: actions/setup-node@v4.0.0
       with:
          node-version: 20

     - name: Checking Installed Node version
       run: |
          echo "node -v"
          echo "npm -v"


     - name: Install Express
       uses: prafulla-codes/express-autodocs@v0.0.2

  test-app:
       runs-on: ubuntu-latest
       name: Simple test
       steps:
         - name: Testing
           run: echo "Running a Test"
   
       
       
       

     
